/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: update_metadata.proto */

#ifndef PROTOBUF_C_update_5fmetadata_2eproto__INCLUDED
#define PROTOBUF_C_update_5fmetadata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

typedef struct ChromeosUpdateEngine__Extent ChromeosUpdateEngine__Extent;
typedef struct ChromeosUpdateEngine__Signatures
    ChromeosUpdateEngine__Signatures;
typedef struct ChromeosUpdateEngine__Signatures__Signature
    ChromeosUpdateEngine__Signatures__Signature;
typedef struct ChromeosUpdateEngine__PartitionInfo
    ChromeosUpdateEngine__PartitionInfo;
typedef struct ChromeosUpdateEngine__InstallOperation
    ChromeosUpdateEngine__InstallOperation;
typedef struct ChromeosUpdateEngine__CowMergeOperation
    ChromeosUpdateEngine__CowMergeOperation;
typedef struct ChromeosUpdateEngine__PartitionUpdate
    ChromeosUpdateEngine__PartitionUpdate;
typedef struct ChromeosUpdateEngine__DynamicPartitionGroup
    ChromeosUpdateEngine__DynamicPartitionGroup;
typedef struct ChromeosUpdateEngine__VABCFeatureSet
    ChromeosUpdateEngine__VABCFeatureSet;
typedef struct ChromeosUpdateEngine__DynamicPartitionMetadata
    ChromeosUpdateEngine__DynamicPartitionMetadata;
typedef struct ChromeosUpdateEngine__ApexInfo ChromeosUpdateEngine__ApexInfo;
typedef struct ChromeosUpdateEngine__ApexMetadata
    ChromeosUpdateEngine__ApexMetadata;
typedef struct ChromeosUpdateEngine__DeltaArchiveManifest
    ChromeosUpdateEngine__DeltaArchiveManifest;

/* --- enums --- */

typedef enum _ChromeosUpdateEngine__InstallOperation__Type {
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE = 0,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE_BZ = 1,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__MOVE = 2,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__BSDIFF = 3,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__SOURCE_COPY = 4,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__SOURCE_BSDIFF = 5,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE_XZ = 8,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZERO = 6,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__DISCARD = 7,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__BROTLI_BSDIFF = 10,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__PUFFDIFF = 9,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZUCCHINI = 11,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__LZ4DIFF_BSDIFF = 12,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__LZ4DIFF_PUFFDIFF = 13,
  CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZSTD =
      14 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(
          CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE)
} ChromeosUpdateEngine__InstallOperation__Type;
typedef enum _ChromeosUpdateEngine__CowMergeOperation__Type {
  CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_COPY = 0,
  CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_XOR = 1,
  CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_REPLACE =
      2 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(
          CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE)
} ChromeosUpdateEngine__CowMergeOperation__Type;

/* --- messages --- */

struct ChromeosUpdateEngine__Extent {
  ProtobufCMessage base;
  protobuf_c_boolean has_start_block;
  uint64_t start_block;
  protobuf_c_boolean has_num_blocks;
  uint64_t num_blocks;
};
#define CHROMEOS_UPDATE_ENGINE__EXTENT__INIT                                   \
  {PROTOBUF_C_MESSAGE_INIT(&chromeos_update_engine__extent__descriptor), 0, 0, \
   0, 0}

struct ChromeosUpdateEngine__Signatures__Signature {
  ProtobufCMessage base;
  protobuf_c_boolean has_version PROTOBUF_C__DEPRECATED;
  uint32_t version PROTOBUF_C__DEPRECATED;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
  protobuf_c_boolean has_unpadded_signature_size;
  uint32_t unpadded_signature_size;
};
#define CHROMEOS_UPDATE_ENGINE__SIGNATURES__SIGNATURE__INIT                    \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__signatures__signature__descriptor),            \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   {0, NULL},                                                                  \
   0,                                                                          \
   0}

struct ChromeosUpdateEngine__Signatures {
  ProtobufCMessage base;
  size_t n_signatures;
  ChromeosUpdateEngine__Signatures__Signature **signatures;
};
#define CHROMEOS_UPDATE_ENGINE__SIGNATURES__INIT                               \
  {PROTOBUF_C_MESSAGE_INIT(&chromeos_update_engine__signatures__descriptor),   \
   0, NULL}

struct ChromeosUpdateEngine__PartitionInfo {
  ProtobufCMessage base;
  protobuf_c_boolean has_size;
  uint64_t size;
  protobuf_c_boolean has_hash;
  ProtobufCBinaryData hash;
};
#define CHROMEOS_UPDATE_ENGINE__PARTITION_INFO__INIT                           \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(                                                   \
        &chromeos_update_engine__partition_info__descriptor)                   \
    , 0, 0, 0, { 0, NULL }                                                     \
  }

struct ChromeosUpdateEngine__InstallOperation {
  ProtobufCMessage base;
  ChromeosUpdateEngine__InstallOperation__Type type;
  protobuf_c_boolean has_data_offset;
  uint64_t data_offset;
  protobuf_c_boolean has_data_length;
  uint64_t data_length;
  size_t n_src_extents;
  ChromeosUpdateEngine__Extent **src_extents;
  protobuf_c_boolean has_src_length;
  uint64_t src_length;
  size_t n_dst_extents;
  ChromeosUpdateEngine__Extent **dst_extents;
  protobuf_c_boolean has_dst_length;
  uint64_t dst_length;
  protobuf_c_boolean has_data_sha256_hash;
  ProtobufCBinaryData data_sha256_hash;
  protobuf_c_boolean has_src_sha256_hash;
  ProtobufCBinaryData src_sha256_hash;
};
#define CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__INIT                        \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(                                                   \
        &chromeos_update_engine__install_operation__descriptor)                \
    , CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE, 0, 0, 0, 0, 0, \
        NULL, 0, 0, 0, NULL, 0, 0, 0, {0, NULL}, 0, {                          \
      0, NULL                                                                  \
    }                                                                          \
  }

struct ChromeosUpdateEngine__CowMergeOperation {
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  ChromeosUpdateEngine__CowMergeOperation__Type type;
  ChromeosUpdateEngine__Extent *src_extent;
  ChromeosUpdateEngine__Extent *dst_extent;
  protobuf_c_boolean has_src_offset;
  uint32_t src_offset;
};
#define CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__INIT                      \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__cow_merge_operation__descriptor),              \
   0,                                                                          \
   CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_COPY,                \
   NULL,                                                                       \
   NULL,                                                                       \
   0,                                                                          \
   0}

struct ChromeosUpdateEngine__PartitionUpdate {
  ProtobufCMessage base;
  char *partition_name;
  protobuf_c_boolean has_run_postinstall;
  protobuf_c_boolean run_postinstall;
  char *postinstall_path;
  char *filesystem_type;
  size_t n_new_partition_signature;
  ChromeosUpdateEngine__Signatures__Signature **new_partition_signature;
  ChromeosUpdateEngine__PartitionInfo *old_partition_info;
  ChromeosUpdateEngine__PartitionInfo *new_partition_info;
  size_t n_operations;
  ChromeosUpdateEngine__InstallOperation **operations;
  protobuf_c_boolean has_postinstall_optional;
  protobuf_c_boolean postinstall_optional;
  ChromeosUpdateEngine__Extent *hash_tree_data_extent;
  ChromeosUpdateEngine__Extent *hash_tree_extent;
  char *hash_tree_algorithm;
  protobuf_c_boolean has_hash_tree_salt;
  ProtobufCBinaryData hash_tree_salt;
  ChromeosUpdateEngine__Extent *fec_data_extent;
  ChromeosUpdateEngine__Extent *fec_extent;
  protobuf_c_boolean has_fec_roots;
  uint32_t fec_roots;
  char *version;
  size_t n_merge_operations;
  ChromeosUpdateEngine__CowMergeOperation **merge_operations;
  protobuf_c_boolean has_estimate_cow_size;
  uint64_t estimate_cow_size;
  protobuf_c_boolean has_estimate_op_count_max;
  uint64_t estimate_op_count_max;
};
#define CHROMEOS_UPDATE_ENGINE__PARTITION_UPDATE__INIT                         \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__partition_update__descriptor),                 \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   NULL,                                                                       \
   0,                                                                          \
   NULL,                                                                       \
   NULL,                                                                       \
   NULL,                                                                       \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   NULL,                                                                       \
   NULL,                                                                       \
   0,                                                                          \
   {0, NULL},                                                                  \
   NULL,                                                                       \
   NULL,                                                                       \
   0,                                                                          \
   2u,                                                                         \
   NULL,                                                                       \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0}

struct ChromeosUpdateEngine__DynamicPartitionGroup {
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_size;
  uint64_t size;
  size_t n_partition_names;
  char **partition_names;
};
#define CHROMEOS_UPDATE_ENGINE__DYNAMIC_PARTITION_GROUP__INIT                  \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__dynamic_partition_group__descriptor),          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   NULL}

struct ChromeosUpdateEngine__VABCFeatureSet {
  ProtobufCMessage base;
  protobuf_c_boolean has_threaded;
  protobuf_c_boolean threaded;
  protobuf_c_boolean has_batch_writes;
  protobuf_c_boolean batch_writes;
};
#define CHROMEOS_UPDATE_ENGINE__VABCFEATURE_SET__INIT                          \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__vabcfeature_set__descriptor),                  \
   0, 0, 0, 0}

struct ChromeosUpdateEngine__DynamicPartitionMetadata {
  ProtobufCMessage base;
  size_t n_groups;
  ChromeosUpdateEngine__DynamicPartitionGroup **groups;
  protobuf_c_boolean has_snapshot_enabled;
  protobuf_c_boolean snapshot_enabled;
  protobuf_c_boolean has_vabc_enabled;
  protobuf_c_boolean vabc_enabled;
  char *vabc_compression_param;
  protobuf_c_boolean has_cow_version;
  uint32_t cow_version;
  ChromeosUpdateEngine__VABCFeatureSet *vabc_feature_set;
  protobuf_c_boolean has_compression_factor;
  uint64_t compression_factor;
};
#define CHROMEOS_UPDATE_ENGINE__DYNAMIC_PARTITION_METADATA__INIT               \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__dynamic_partition_metadata__descriptor),       \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0}

struct ChromeosUpdateEngine__ApexInfo {
  ProtobufCMessage base;
  char *package_name;
  protobuf_c_boolean has_version;
  int64_t version;
  protobuf_c_boolean has_is_compressed;
  protobuf_c_boolean is_compressed;
  protobuf_c_boolean has_decompressed_size;
  int64_t decompressed_size;
};
#define CHROMEOS_UPDATE_ENGINE__APEX_INFO__INIT                                \
  {PROTOBUF_C_MESSAGE_INIT(&chromeos_update_engine__apex_info__descriptor),    \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0}

struct ChromeosUpdateEngine__ApexMetadata {
  ProtobufCMessage base;
  size_t n_apex_info;
  ChromeosUpdateEngine__ApexInfo **apex_info;
};
#define CHROMEOS_UPDATE_ENGINE__APEX_METADATA__INIT                            \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__apex_metadata__descriptor),                    \
   0, NULL}

struct ChromeosUpdateEngine__DeltaArchiveManifest {
  ProtobufCMessage base;
  protobuf_c_boolean has_block_size;
  uint32_t block_size;
  protobuf_c_boolean has_signatures_offset;
  uint64_t signatures_offset;
  protobuf_c_boolean has_signatures_size;
  uint64_t signatures_size;
  protobuf_c_boolean has_minor_version;
  uint32_t minor_version;
  size_t n_partitions;
  ChromeosUpdateEngine__PartitionUpdate **partitions;
  protobuf_c_boolean has_max_timestamp;
  int64_t max_timestamp;
  ChromeosUpdateEngine__DynamicPartitionMetadata *dynamic_partition_metadata;
  protobuf_c_boolean has_partial_update;
  protobuf_c_boolean partial_update;
  size_t n_apex_info;
  ChromeosUpdateEngine__ApexInfo **apex_info;
  char *security_patch_level;
};
#define CHROMEOS_UPDATE_ENGINE__DELTA_ARCHIVE_MANIFEST__INIT                   \
  {PROTOBUF_C_MESSAGE_INIT(                                                    \
       &chromeos_update_engine__delta_archive_manifest__descriptor),           \
   0,                                                                          \
   4096u,                                                                      \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   0u,                                                                         \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   0,                                                                          \
   0,                                                                          \
   0,                                                                          \
   NULL,                                                                       \
   NULL}

/* ChromeosUpdateEngine__Extent methods */
void chromeos_update_engine__extent__init(
    ChromeosUpdateEngine__Extent *message);
size_t chromeos_update_engine__extent__get_packed_size(
    const ChromeosUpdateEngine__Extent *message);
size_t chromeos_update_engine__extent__pack(
    const ChromeosUpdateEngine__Extent *message, uint8_t *out);
size_t chromeos_update_engine__extent__pack_to_buffer(
    const ChromeosUpdateEngine__Extent *message, ProtobufCBuffer *buffer);
ChromeosUpdateEngine__Extent *
chromeos_update_engine__extent__unpack(ProtobufCAllocator *allocator,
                                       size_t len, const uint8_t *data);
void chromeos_update_engine__extent__free_unpacked(
    ChromeosUpdateEngine__Extent *message, ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__Signatures__Signature methods */
void chromeos_update_engine__signatures__signature__init(
    ChromeosUpdateEngine__Signatures__Signature *message);
/* ChromeosUpdateEngine__Signatures methods */
void chromeos_update_engine__signatures__init(
    ChromeosUpdateEngine__Signatures *message);
size_t chromeos_update_engine__signatures__get_packed_size(
    const ChromeosUpdateEngine__Signatures *message);
size_t chromeos_update_engine__signatures__pack(
    const ChromeosUpdateEngine__Signatures *message, uint8_t *out);
size_t chromeos_update_engine__signatures__pack_to_buffer(
    const ChromeosUpdateEngine__Signatures *message, ProtobufCBuffer *buffer);
ChromeosUpdateEngine__Signatures *
chromeos_update_engine__signatures__unpack(ProtobufCAllocator *allocator,
                                           size_t len, const uint8_t *data);
void chromeos_update_engine__signatures__free_unpacked(
    ChromeosUpdateEngine__Signatures *message, ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__PartitionInfo methods */
void chromeos_update_engine__partition_info__init(
    ChromeosUpdateEngine__PartitionInfo *message);
size_t chromeos_update_engine__partition_info__get_packed_size(
    const ChromeosUpdateEngine__PartitionInfo *message);
size_t chromeos_update_engine__partition_info__pack(
    const ChromeosUpdateEngine__PartitionInfo *message, uint8_t *out);
size_t chromeos_update_engine__partition_info__pack_to_buffer(
    const ChromeosUpdateEngine__PartitionInfo *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__PartitionInfo *
chromeos_update_engine__partition_info__unpack(ProtobufCAllocator *allocator,
                                               size_t len, const uint8_t *data);
void chromeos_update_engine__partition_info__free_unpacked(
    ChromeosUpdateEngine__PartitionInfo *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__InstallOperation methods */
void chromeos_update_engine__install_operation__init(
    ChromeosUpdateEngine__InstallOperation *message);
size_t chromeos_update_engine__install_operation__get_packed_size(
    const ChromeosUpdateEngine__InstallOperation *message);
size_t chromeos_update_engine__install_operation__pack(
    const ChromeosUpdateEngine__InstallOperation *message, uint8_t *out);
size_t chromeos_update_engine__install_operation__pack_to_buffer(
    const ChromeosUpdateEngine__InstallOperation *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__InstallOperation *
chromeos_update_engine__install_operation__unpack(ProtobufCAllocator *allocator,
                                                  size_t len,
                                                  const uint8_t *data);
void chromeos_update_engine__install_operation__free_unpacked(
    ChromeosUpdateEngine__InstallOperation *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__CowMergeOperation methods */
void chromeos_update_engine__cow_merge_operation__init(
    ChromeosUpdateEngine__CowMergeOperation *message);
size_t chromeos_update_engine__cow_merge_operation__get_packed_size(
    const ChromeosUpdateEngine__CowMergeOperation *message);
size_t chromeos_update_engine__cow_merge_operation__pack(
    const ChromeosUpdateEngine__CowMergeOperation *message, uint8_t *out);
size_t chromeos_update_engine__cow_merge_operation__pack_to_buffer(
    const ChromeosUpdateEngine__CowMergeOperation *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__CowMergeOperation *
chromeos_update_engine__cow_merge_operation__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void chromeos_update_engine__cow_merge_operation__free_unpacked(
    ChromeosUpdateEngine__CowMergeOperation *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__PartitionUpdate methods */
void chromeos_update_engine__partition_update__init(
    ChromeosUpdateEngine__PartitionUpdate *message);
size_t chromeos_update_engine__partition_update__get_packed_size(
    const ChromeosUpdateEngine__PartitionUpdate *message);
size_t chromeos_update_engine__partition_update__pack(
    const ChromeosUpdateEngine__PartitionUpdate *message, uint8_t *out);
size_t chromeos_update_engine__partition_update__pack_to_buffer(
    const ChromeosUpdateEngine__PartitionUpdate *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__PartitionUpdate *
chromeos_update_engine__partition_update__unpack(ProtobufCAllocator *allocator,
                                                 size_t len,
                                                 const uint8_t *data);
void chromeos_update_engine__partition_update__free_unpacked(
    ChromeosUpdateEngine__PartitionUpdate *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__DynamicPartitionGroup methods */
void chromeos_update_engine__dynamic_partition_group__init(
    ChromeosUpdateEngine__DynamicPartitionGroup *message);
size_t chromeos_update_engine__dynamic_partition_group__get_packed_size(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message);
size_t chromeos_update_engine__dynamic_partition_group__pack(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message, uint8_t *out);
size_t chromeos_update_engine__dynamic_partition_group__pack_to_buffer(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__DynamicPartitionGroup *
chromeos_update_engine__dynamic_partition_group__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void chromeos_update_engine__dynamic_partition_group__free_unpacked(
    ChromeosUpdateEngine__DynamicPartitionGroup *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__VABCFeatureSet methods */
void chromeos_update_engine__vabcfeature_set__init(
    ChromeosUpdateEngine__VABCFeatureSet *message);
size_t chromeos_update_engine__vabcfeature_set__get_packed_size(
    const ChromeosUpdateEngine__VABCFeatureSet *message);
size_t chromeos_update_engine__vabcfeature_set__pack(
    const ChromeosUpdateEngine__VABCFeatureSet *message, uint8_t *out);
size_t chromeos_update_engine__vabcfeature_set__pack_to_buffer(
    const ChromeosUpdateEngine__VABCFeatureSet *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__VABCFeatureSet *
chromeos_update_engine__vabcfeature_set__unpack(ProtobufCAllocator *allocator,
                                                size_t len,
                                                const uint8_t *data);
void chromeos_update_engine__vabcfeature_set__free_unpacked(
    ChromeosUpdateEngine__VABCFeatureSet *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__DynamicPartitionMetadata methods */
void chromeos_update_engine__dynamic_partition_metadata__init(
    ChromeosUpdateEngine__DynamicPartitionMetadata *message);
size_t chromeos_update_engine__dynamic_partition_metadata__get_packed_size(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message);
size_t chromeos_update_engine__dynamic_partition_metadata__pack(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    uint8_t *out);
size_t chromeos_update_engine__dynamic_partition_metadata__pack_to_buffer(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__DynamicPartitionMetadata *
chromeos_update_engine__dynamic_partition_metadata__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void chromeos_update_engine__dynamic_partition_metadata__free_unpacked(
    ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__ApexInfo methods */
void chromeos_update_engine__apex_info__init(
    ChromeosUpdateEngine__ApexInfo *message);
size_t chromeos_update_engine__apex_info__get_packed_size(
    const ChromeosUpdateEngine__ApexInfo *message);
size_t chromeos_update_engine__apex_info__pack(
    const ChromeosUpdateEngine__ApexInfo *message, uint8_t *out);
size_t chromeos_update_engine__apex_info__pack_to_buffer(
    const ChromeosUpdateEngine__ApexInfo *message, ProtobufCBuffer *buffer);
ChromeosUpdateEngine__ApexInfo *
chromeos_update_engine__apex_info__unpack(ProtobufCAllocator *allocator,
                                          size_t len, const uint8_t *data);
void chromeos_update_engine__apex_info__free_unpacked(
    ChromeosUpdateEngine__ApexInfo *message, ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__ApexMetadata methods */
void chromeos_update_engine__apex_metadata__init(
    ChromeosUpdateEngine__ApexMetadata *message);
size_t chromeos_update_engine__apex_metadata__get_packed_size(
    const ChromeosUpdateEngine__ApexMetadata *message);
size_t chromeos_update_engine__apex_metadata__pack(
    const ChromeosUpdateEngine__ApexMetadata *message, uint8_t *out);
size_t chromeos_update_engine__apex_metadata__pack_to_buffer(
    const ChromeosUpdateEngine__ApexMetadata *message, ProtobufCBuffer *buffer);
ChromeosUpdateEngine__ApexMetadata *
chromeos_update_engine__apex_metadata__unpack(ProtobufCAllocator *allocator,
                                              size_t len, const uint8_t *data);
void chromeos_update_engine__apex_metadata__free_unpacked(
    ChromeosUpdateEngine__ApexMetadata *message, ProtobufCAllocator *allocator);
/* ChromeosUpdateEngine__DeltaArchiveManifest methods */
void chromeos_update_engine__delta_archive_manifest__init(
    ChromeosUpdateEngine__DeltaArchiveManifest *message);
size_t chromeos_update_engine__delta_archive_manifest__get_packed_size(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message);
size_t chromeos_update_engine__delta_archive_manifest__pack(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message, uint8_t *out);
size_t chromeos_update_engine__delta_archive_manifest__pack_to_buffer(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message,
    ProtobufCBuffer *buffer);
ChromeosUpdateEngine__DeltaArchiveManifest *
chromeos_update_engine__delta_archive_manifest__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void chromeos_update_engine__delta_archive_manifest__free_unpacked(
    ChromeosUpdateEngine__DeltaArchiveManifest *message,
    ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChromeosUpdateEngine__Extent_Closure)(
    const ChromeosUpdateEngine__Extent *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__Signatures__Signature_Closure)(
    const ChromeosUpdateEngine__Signatures__Signature *message,
    void *closure_data);
typedef void (*ChromeosUpdateEngine__Signatures_Closure)(
    const ChromeosUpdateEngine__Signatures *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__PartitionInfo_Closure)(
    const ChromeosUpdateEngine__PartitionInfo *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__InstallOperation_Closure)(
    const ChromeosUpdateEngine__InstallOperation *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__CowMergeOperation_Closure)(
    const ChromeosUpdateEngine__CowMergeOperation *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__PartitionUpdate_Closure)(
    const ChromeosUpdateEngine__PartitionUpdate *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__DynamicPartitionGroup_Closure)(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message,
    void *closure_data);
typedef void (*ChromeosUpdateEngine__VABCFeatureSet_Closure)(
    const ChromeosUpdateEngine__VABCFeatureSet *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__DynamicPartitionMetadata_Closure)(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    void *closure_data);
typedef void (*ChromeosUpdateEngine__ApexInfo_Closure)(
    const ChromeosUpdateEngine__ApexInfo *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__ApexMetadata_Closure)(
    const ChromeosUpdateEngine__ApexMetadata *message, void *closure_data);
typedef void (*ChromeosUpdateEngine__DeltaArchiveManifest_Closure)(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message,
    void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor
    chromeos_update_engine__extent__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__signatures__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__signatures__signature__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__partition_info__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__install_operation__descriptor;
extern const ProtobufCEnumDescriptor
    chromeos_update_engine__install_operation__type__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__cow_merge_operation__descriptor;
extern const ProtobufCEnumDescriptor
    chromeos_update_engine__cow_merge_operation__type__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__partition_update__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__dynamic_partition_group__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__vabcfeature_set__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__dynamic_partition_metadata__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__apex_info__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__apex_metadata__descriptor;
extern const ProtobufCMessageDescriptor
    chromeos_update_engine__delta_archive_manifest__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_update_5fmetadata_2eproto__INCLUDED */
