/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: update_metadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "update_metadata.pb-c.h"
void chromeos_update_engine__extent__init(
    ChromeosUpdateEngine__Extent *message) {
  static const ChromeosUpdateEngine__Extent init_value =
      CHROMEOS_UPDATE_ENGINE__EXTENT__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__extent__get_packed_size(
    const ChromeosUpdateEngine__Extent *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__extent__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__extent__pack(
    const ChromeosUpdateEngine__Extent *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__extent__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__extent__pack_to_buffer(
    const ChromeosUpdateEngine__Extent *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__extent__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__Extent *
chromeos_update_engine__extent__unpack(ProtobufCAllocator *allocator,
                                       size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__Extent *)protobuf_c_message_unpack(
      &chromeos_update_engine__extent__descriptor, allocator, len, data);
}
void chromeos_update_engine__extent__free_unpacked(
    ChromeosUpdateEngine__Extent *message, ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__extent__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__signatures__signature__init(
    ChromeosUpdateEngine__Signatures__Signature *message) {
  static const ChromeosUpdateEngine__Signatures__Signature init_value =
      CHROMEOS_UPDATE_ENGINE__SIGNATURES__SIGNATURE__INIT;
  *message = init_value;
}
void chromeos_update_engine__signatures__init(
    ChromeosUpdateEngine__Signatures *message) {
  static const ChromeosUpdateEngine__Signatures init_value =
      CHROMEOS_UPDATE_ENGINE__SIGNATURES__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__signatures__get_packed_size(
    const ChromeosUpdateEngine__Signatures *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__signatures__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__signatures__pack(
    const ChromeosUpdateEngine__Signatures *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__signatures__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__signatures__pack_to_buffer(
    const ChromeosUpdateEngine__Signatures *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__signatures__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__Signatures *
chromeos_update_engine__signatures__unpack(ProtobufCAllocator *allocator,
                                           size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__Signatures *)protobuf_c_message_unpack(
      &chromeos_update_engine__signatures__descriptor, allocator, len, data);
}
void chromeos_update_engine__signatures__free_unpacked(
    ChromeosUpdateEngine__Signatures *message, ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__signatures__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__partition_info__init(
    ChromeosUpdateEngine__PartitionInfo *message) {
  static const ChromeosUpdateEngine__PartitionInfo init_value =
      CHROMEOS_UPDATE_ENGINE__PARTITION_INFO__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__partition_info__get_packed_size(
    const ChromeosUpdateEngine__PartitionInfo *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_info__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__partition_info__pack(
    const ChromeosUpdateEngine__PartitionInfo *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_info__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__partition_info__pack_to_buffer(
    const ChromeosUpdateEngine__PartitionInfo *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_info__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__PartitionInfo *
chromeos_update_engine__partition_info__unpack(ProtobufCAllocator *allocator,
                                               size_t len,
                                               const uint8_t *data) {
  return (ChromeosUpdateEngine__PartitionInfo *)protobuf_c_message_unpack(
      &chromeos_update_engine__partition_info__descriptor, allocator, len,
      data);
}
void chromeos_update_engine__partition_info__free_unpacked(
    ChromeosUpdateEngine__PartitionInfo *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_info__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__install_operation__init(
    ChromeosUpdateEngine__InstallOperation *message) {
  static const ChromeosUpdateEngine__InstallOperation init_value =
      CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__install_operation__get_packed_size(
    const ChromeosUpdateEngine__InstallOperation *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__install_operation__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__install_operation__pack(
    const ChromeosUpdateEngine__InstallOperation *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__install_operation__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__install_operation__pack_to_buffer(
    const ChromeosUpdateEngine__InstallOperation *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__install_operation__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__InstallOperation *
chromeos_update_engine__install_operation__unpack(ProtobufCAllocator *allocator,
                                                  size_t len,
                                                  const uint8_t *data) {
  return (ChromeosUpdateEngine__InstallOperation *)protobuf_c_message_unpack(
      &chromeos_update_engine__install_operation__descriptor, allocator, len,
      data);
}
void chromeos_update_engine__install_operation__free_unpacked(
    ChromeosUpdateEngine__InstallOperation *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__install_operation__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__cow_merge_operation__init(
    ChromeosUpdateEngine__CowMergeOperation *message) {
  static const ChromeosUpdateEngine__CowMergeOperation init_value =
      CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__cow_merge_operation__get_packed_size(
    const ChromeosUpdateEngine__CowMergeOperation *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__cow_merge_operation__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__cow_merge_operation__pack(
    const ChromeosUpdateEngine__CowMergeOperation *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__cow_merge_operation__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__cow_merge_operation__pack_to_buffer(
    const ChromeosUpdateEngine__CowMergeOperation *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__cow_merge_operation__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__CowMergeOperation *
chromeos_update_engine__cow_merge_operation__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__CowMergeOperation *)protobuf_c_message_unpack(
      &chromeos_update_engine__cow_merge_operation__descriptor, allocator, len,
      data);
}
void chromeos_update_engine__cow_merge_operation__free_unpacked(
    ChromeosUpdateEngine__CowMergeOperation *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__cow_merge_operation__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__partition_update__init(
    ChromeosUpdateEngine__PartitionUpdate *message) {
  static const ChromeosUpdateEngine__PartitionUpdate init_value =
      CHROMEOS_UPDATE_ENGINE__PARTITION_UPDATE__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__partition_update__get_packed_size(
    const ChromeosUpdateEngine__PartitionUpdate *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_update__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__partition_update__pack(
    const ChromeosUpdateEngine__PartitionUpdate *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_update__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__partition_update__pack_to_buffer(
    const ChromeosUpdateEngine__PartitionUpdate *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_update__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__PartitionUpdate *
chromeos_update_engine__partition_update__unpack(ProtobufCAllocator *allocator,
                                                 size_t len,
                                                 const uint8_t *data) {
  return (ChromeosUpdateEngine__PartitionUpdate *)protobuf_c_message_unpack(
      &chromeos_update_engine__partition_update__descriptor, allocator, len,
      data);
}
void chromeos_update_engine__partition_update__free_unpacked(
    ChromeosUpdateEngine__PartitionUpdate *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__partition_update__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__dynamic_partition_group__init(
    ChromeosUpdateEngine__DynamicPartitionGroup *message) {
  static const ChromeosUpdateEngine__DynamicPartitionGroup init_value =
      CHROMEOS_UPDATE_ENGINE__DYNAMIC_PARTITION_GROUP__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__dynamic_partition_group__get_packed_size(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_group__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__dynamic_partition_group__pack(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_group__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__dynamic_partition_group__pack_to_buffer(
    const ChromeosUpdateEngine__DynamicPartitionGroup *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_group__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__DynamicPartitionGroup *
chromeos_update_engine__dynamic_partition_group__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__DynamicPartitionGroup *)
      protobuf_c_message_unpack(
          &chromeos_update_engine__dynamic_partition_group__descriptor,
          allocator, len, data);
}
void chromeos_update_engine__dynamic_partition_group__free_unpacked(
    ChromeosUpdateEngine__DynamicPartitionGroup *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_group__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__vabcfeature_set__init(
    ChromeosUpdateEngine__VABCFeatureSet *message) {
  static const ChromeosUpdateEngine__VABCFeatureSet init_value =
      CHROMEOS_UPDATE_ENGINE__VABCFEATURE_SET__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__vabcfeature_set__get_packed_size(
    const ChromeosUpdateEngine__VABCFeatureSet *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__vabcfeature_set__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__vabcfeature_set__pack(
    const ChromeosUpdateEngine__VABCFeatureSet *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__vabcfeature_set__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__vabcfeature_set__pack_to_buffer(
    const ChromeosUpdateEngine__VABCFeatureSet *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__vabcfeature_set__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__VABCFeatureSet *
chromeos_update_engine__vabcfeature_set__unpack(ProtobufCAllocator *allocator,
                                                size_t len,
                                                const uint8_t *data) {
  return (ChromeosUpdateEngine__VABCFeatureSet *)protobuf_c_message_unpack(
      &chromeos_update_engine__vabcfeature_set__descriptor, allocator, len,
      data);
}
void chromeos_update_engine__vabcfeature_set__free_unpacked(
    ChromeosUpdateEngine__VABCFeatureSet *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__vabcfeature_set__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__dynamic_partition_metadata__init(
    ChromeosUpdateEngine__DynamicPartitionMetadata *message) {
  static const ChromeosUpdateEngine__DynamicPartitionMetadata init_value =
      CHROMEOS_UPDATE_ENGINE__DYNAMIC_PARTITION_METADATA__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__dynamic_partition_metadata__get_packed_size(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_metadata__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__dynamic_partition_metadata__pack(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_metadata__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__dynamic_partition_metadata__pack_to_buffer(
    const ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__DynamicPartitionMetadata *
chromeos_update_engine__dynamic_partition_metadata__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__DynamicPartitionMetadata *)
      protobuf_c_message_unpack(
          &chromeos_update_engine__dynamic_partition_metadata__descriptor,
          allocator, len, data);
}
void chromeos_update_engine__dynamic_partition_metadata__free_unpacked(
    ChromeosUpdateEngine__DynamicPartitionMetadata *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__dynamic_partition_metadata__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__apex_info__init(
    ChromeosUpdateEngine__ApexInfo *message) {
  static const ChromeosUpdateEngine__ApexInfo init_value =
      CHROMEOS_UPDATE_ENGINE__APEX_INFO__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__apex_info__get_packed_size(
    const ChromeosUpdateEngine__ApexInfo *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_info__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__apex_info__pack(
    const ChromeosUpdateEngine__ApexInfo *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_info__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__apex_info__pack_to_buffer(
    const ChromeosUpdateEngine__ApexInfo *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_info__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__ApexInfo *
chromeos_update_engine__apex_info__unpack(ProtobufCAllocator *allocator,
                                          size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__ApexInfo *)protobuf_c_message_unpack(
      &chromeos_update_engine__apex_info__descriptor, allocator, len, data);
}
void chromeos_update_engine__apex_info__free_unpacked(
    ChromeosUpdateEngine__ApexInfo *message, ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_info__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__apex_metadata__init(
    ChromeosUpdateEngine__ApexMetadata *message) {
  static const ChromeosUpdateEngine__ApexMetadata init_value =
      CHROMEOS_UPDATE_ENGINE__APEX_METADATA__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__apex_metadata__get_packed_size(
    const ChromeosUpdateEngine__ApexMetadata *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_metadata__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__apex_metadata__pack(
    const ChromeosUpdateEngine__ApexMetadata *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_metadata__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__apex_metadata__pack_to_buffer(
    const ChromeosUpdateEngine__ApexMetadata *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__ApexMetadata *
chromeos_update_engine__apex_metadata__unpack(ProtobufCAllocator *allocator,
                                              size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__ApexMetadata *)protobuf_c_message_unpack(
      &chromeos_update_engine__apex_metadata__descriptor, allocator, len, data);
}
void chromeos_update_engine__apex_metadata__free_unpacked(
    ChromeosUpdateEngine__ApexMetadata *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__apex_metadata__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void chromeos_update_engine__delta_archive_manifest__init(
    ChromeosUpdateEngine__DeltaArchiveManifest *message) {
  static const ChromeosUpdateEngine__DeltaArchiveManifest init_value =
      CHROMEOS_UPDATE_ENGINE__DELTA_ARCHIVE_MANIFEST__INIT;
  *message = init_value;
}
size_t chromeos_update_engine__delta_archive_manifest__get_packed_size(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__delta_archive_manifest__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t chromeos_update_engine__delta_archive_manifest__pack(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message, uint8_t *out) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__delta_archive_manifest__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t chromeos_update_engine__delta_archive_manifest__pack_to_buffer(
    const ChromeosUpdateEngine__DeltaArchiveManifest *message,
    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor ==
         &chromeos_update_engine__delta_archive_manifest__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
ChromeosUpdateEngine__DeltaArchiveManifest *
chromeos_update_engine__delta_archive_manifest__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (ChromeosUpdateEngine__DeltaArchiveManifest *)
      protobuf_c_message_unpack(
          &chromeos_update_engine__delta_archive_manifest__descriptor,
          allocator, len, data);
}
void chromeos_update_engine__delta_archive_manifest__free_unpacked(
    ChromeosUpdateEngine__DeltaArchiveManifest *message,
    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor ==
         &chromeos_update_engine__delta_archive_manifest__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor
    chromeos_update_engine__extent__field_descriptors[2] = {
        {
            "start_block", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__Extent, has_start_block),
            offsetof(ChromeosUpdateEngine__Extent, start_block), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "num_blocks", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__Extent, has_num_blocks),
            offsetof(ChromeosUpdateEngine__Extent, num_blocks), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned chromeos_update_engine__extent__field_indices_by_name[] =
    {
        1, /* field[1] = num_blocks */
        0, /* field[0] = start_block */
};
static const ProtobufCIntRange
    chromeos_update_engine__extent__number_ranges[1 + 1] = {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor chromeos_update_engine__extent__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "chromeos_update_engine.Extent",
    "Extent",
    "ChromeosUpdateEngine__Extent",
    "chromeos_update_engine",
    sizeof(ChromeosUpdateEngine__Extent),
    2,
    chromeos_update_engine__extent__field_descriptors,
    chromeos_update_engine__extent__field_indices_by_name,
    1,
    chromeos_update_engine__extent__number_ranges,
    (ProtobufCMessageInit)chromeos_update_engine__extent__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__signatures__signature__field_descriptors[3] = {
        {
            "version", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__Signatures__Signature, has_version),
            offsetof(ChromeosUpdateEngine__Signatures__Signature, version),
            NULL, NULL, PROTOBUF_C_FIELD_FLAG_DEPRECATED, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "data", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BYTES,
            offsetof(ChromeosUpdateEngine__Signatures__Signature, has_data),
            offsetof(ChromeosUpdateEngine__Signatures__Signature, data), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "unpadded_signature_size", 3, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_FIXED32,
            offsetof(ChromeosUpdateEngine__Signatures__Signature,
                     has_unpadded_signature_size),
            offsetof(ChromeosUpdateEngine__Signatures__Signature,
                     unpadded_signature_size),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__signatures__signature__field_indices_by_name[] = {
        1, /* field[1] = data */
        2, /* field[2] = unpadded_signature_size */
        0, /* field[0] = version */
};
static const ProtobufCIntRange
    chromeos_update_engine__signatures__signature__number_ranges[1 + 1] = {
        {1, 0}, {0, 3}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__signatures__signature__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.Signatures.Signature",
        "Signature",
        "ChromeosUpdateEngine__Signatures__Signature",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__Signatures__Signature),
        3,
        chromeos_update_engine__signatures__signature__field_descriptors,
        chromeos_update_engine__signatures__signature__field_indices_by_name,
        1,
        chromeos_update_engine__signatures__signature__number_ranges,
        (ProtobufCMessageInit)
            chromeos_update_engine__signatures__signature__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__signatures__field_descriptors[1] = {
        {
            "signatures", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__Signatures, n_signatures),
            offsetof(ChromeosUpdateEngine__Signatures, signatures),
            &chromeos_update_engine__signatures__signature__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__signatures__field_indices_by_name[] = {
        0, /* field[0] = signatures */
};
static const ProtobufCIntRange
    chromeos_update_engine__signatures__number_ranges[1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__signatures__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.Signatures",
        "Signatures",
        "ChromeosUpdateEngine__Signatures",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__Signatures),
        1,
        chromeos_update_engine__signatures__field_descriptors,
        chromeos_update_engine__signatures__field_indices_by_name,
        1,
        chromeos_update_engine__signatures__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__signatures__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__partition_info__field_descriptors[2] = {
        {
            "size", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__PartitionInfo, has_size),
            offsetof(ChromeosUpdateEngine__PartitionInfo, size), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "hash", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BYTES,
            offsetof(ChromeosUpdateEngine__PartitionInfo, has_hash),
            offsetof(ChromeosUpdateEngine__PartitionInfo, hash), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__partition_info__field_indices_by_name[] = {
        1, /* field[1] = hash */
        0, /* field[0] = size */
};
static const ProtobufCIntRange
    chromeos_update_engine__partition_info__number_ranges[1 + 1] = {{1, 0},
                                                                    {0, 2}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__partition_info__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.PartitionInfo",
        "PartitionInfo",
        "ChromeosUpdateEngine__PartitionInfo",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__PartitionInfo),
        2,
        chromeos_update_engine__partition_info__field_descriptors,
        chromeos_update_engine__partition_info__field_indices_by_name,
        1,
        chromeos_update_engine__partition_info__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__partition_info__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCEnumValue
    chromeos_update_engine__install_operation__type__enum_values_by_number[15] =
        {
            {"REPLACE",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE", 0},
            {"REPLACE_BZ",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE_BZ", 1},
            {"MOVE", "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__MOVE",
             2},
            {"BSDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__BSDIFF", 3},
            {"SOURCE_COPY",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__SOURCE_COPY", 4},
            {"SOURCE_BSDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__SOURCE_BSDIFF",
             5},
            {"ZERO", "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZERO",
             6},
            {"DISCARD",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__DISCARD", 7},
            {"REPLACE_XZ",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__REPLACE_XZ", 8},
            {"PUFFDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__PUFFDIFF", 9},
            {"BROTLI_BSDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__BROTLI_BSDIFF",
             10},
            {"ZUCCHINI",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZUCCHINI", 11},
            {"LZ4DIFF_BSDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__LZ4DIFF_BSDIFF",
             12},
            {"LZ4DIFF_PUFFDIFF",
             "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__LZ4DIFF_"
             "PUFFDIFF",
             13},
            {"ZSTD", "CHROMEOS_UPDATE_ENGINE__INSTALL_OPERATION__TYPE__ZSTD",
             14},
};
static const ProtobufCIntRange
    chromeos_update_engine__install_operation__type__value_ranges[] = {{0, 0},
                                                                       {0, 15}};
static const ProtobufCEnumValueIndex
    chromeos_update_engine__install_operation__type__enum_values_by_name[15] = {
        {"BROTLI_BSDIFF", 10},
        {"BSDIFF", 3},
        {"DISCARD", 7},
        {"LZ4DIFF_BSDIFF", 12},
        {"LZ4DIFF_PUFFDIFF", 13},
        {"MOVE", 2},
        {"PUFFDIFF", 9},
        {"REPLACE", 0},
        {"REPLACE_BZ", 1},
        {"REPLACE_XZ", 8},
        {"SOURCE_BSDIFF", 5},
        {"SOURCE_COPY", 4},
        {"ZERO", 6},
        {"ZSTD", 14},
        {"ZUCCHINI", 11},
};
const ProtobufCEnumDescriptor
    chromeos_update_engine__install_operation__type__descriptor = {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.InstallOperation.Type",
        "Type",
        "ChromeosUpdateEngine__InstallOperation__Type",
        "chromeos_update_engine",
        15,
        chromeos_update_engine__install_operation__type__enum_values_by_number,
        15,
        chromeos_update_engine__install_operation__type__enum_values_by_name,
        1,
        chromeos_update_engine__install_operation__type__value_ranges,
        NULL,
        NULL,
        NULL,
        NULL /* reserved[1234] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__install_operation__field_descriptors[9] = {
        {
            "type", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_ENUM,
            0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__InstallOperation, type),
            &chromeos_update_engine__install_operation__type__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "data_offset", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__InstallOperation, has_data_offset),
            offsetof(ChromeosUpdateEngine__InstallOperation, data_offset), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "data_length", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__InstallOperation, has_data_length),
            offsetof(ChromeosUpdateEngine__InstallOperation, data_length), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "src_extents", 4, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__InstallOperation, n_src_extents),
            offsetof(ChromeosUpdateEngine__InstallOperation, src_extents),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "src_length", 5, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__InstallOperation, has_src_length),
            offsetof(ChromeosUpdateEngine__InstallOperation, src_length), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "dst_extents", 6, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__InstallOperation, n_dst_extents),
            offsetof(ChromeosUpdateEngine__InstallOperation, dst_extents),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "dst_length", 7, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__InstallOperation, has_dst_length),
            offsetof(ChromeosUpdateEngine__InstallOperation, dst_length), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "data_sha256_hash", 8, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BYTES,
            offsetof(ChromeosUpdateEngine__InstallOperation,
                     has_data_sha256_hash),
            offsetof(ChromeosUpdateEngine__InstallOperation, data_sha256_hash),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "src_sha256_hash", 9, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BYTES,
            offsetof(ChromeosUpdateEngine__InstallOperation,
                     has_src_sha256_hash),
            offsetof(ChromeosUpdateEngine__InstallOperation, src_sha256_hash),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__install_operation__field_indices_by_name[] = {
        2, /* field[2] = data_length */
        1, /* field[1] = data_offset */
        7, /* field[7] = data_sha256_hash */
        5, /* field[5] = dst_extents */
        6, /* field[6] = dst_length */
        3, /* field[3] = src_extents */
        4, /* field[4] = src_length */
        8, /* field[8] = src_sha256_hash */
        0, /* field[0] = type */
};
static const ProtobufCIntRange
    chromeos_update_engine__install_operation__number_ranges[1 + 1] = {{1, 0},
                                                                       {0, 9}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__install_operation__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.InstallOperation",
        "InstallOperation",
        "ChromeosUpdateEngine__InstallOperation",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__InstallOperation),
        9,
        chromeos_update_engine__install_operation__field_descriptors,
        chromeos_update_engine__install_operation__field_indices_by_name,
        1,
        chromeos_update_engine__install_operation__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__install_operation__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCEnumValue
    chromeos_update_engine__cow_merge_operation__type__enum_values_by_number
        [3] = {
            {"COW_COPY",
             "CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_COPY", 0},
            {"COW_XOR",
             "CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_XOR", 1},
            {"COW_REPLACE",
             "CHROMEOS_UPDATE_ENGINE__COW_MERGE_OPERATION__TYPE__COW_REPLACE",
             2},
};
static const ProtobufCIntRange
    chromeos_update_engine__cow_merge_operation__type__value_ranges[] = {
        {0, 0}, {0, 3}};
static const ProtobufCEnumValueIndex
    chromeos_update_engine__cow_merge_operation__type__enum_values_by_name[3] =
        {
            {"COW_COPY", 0},
            {"COW_REPLACE", 2},
            {"COW_XOR", 1},
};
const ProtobufCEnumDescriptor
    chromeos_update_engine__cow_merge_operation__type__descriptor = {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.CowMergeOperation.Type",
        "Type",
        "ChromeosUpdateEngine__CowMergeOperation__Type",
        "chromeos_update_engine",
        3,
        chromeos_update_engine__cow_merge_operation__type__enum_values_by_number,
        3,
        chromeos_update_engine__cow_merge_operation__type__enum_values_by_name,
        1,
        chromeos_update_engine__cow_merge_operation__type__value_ranges,
        NULL,
        NULL,
        NULL,
        NULL /* reserved[1234] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__cow_merge_operation__field_descriptors[4] = {
        {
            "type", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_ENUM,
            offsetof(ChromeosUpdateEngine__CowMergeOperation, has_type),
            offsetof(ChromeosUpdateEngine__CowMergeOperation, type),
            &chromeos_update_engine__cow_merge_operation__type__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "src_extent", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__CowMergeOperation, src_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "dst_extent", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_MESSAGE,
            0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__CowMergeOperation, dst_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "src_offset", 4, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__CowMergeOperation, has_src_offset),
            offsetof(ChromeosUpdateEngine__CowMergeOperation, src_offset), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__cow_merge_operation__field_indices_by_name[] = {
        2, /* field[2] = dst_extent */
        1, /* field[1] = src_extent */
        3, /* field[3] = src_offset */
        0, /* field[0] = type */
};
static const ProtobufCIntRange
    chromeos_update_engine__cow_merge_operation__number_ranges[1 + 1] = {
        {1, 0}, {0, 4}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__cow_merge_operation__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.CowMergeOperation",
        "CowMergeOperation",
        "ChromeosUpdateEngine__CowMergeOperation",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__CowMergeOperation),
        4,
        chromeos_update_engine__cow_merge_operation__field_descriptors,
        chromeos_update_engine__cow_merge_operation__field_indices_by_name,
        1,
        chromeos_update_engine__cow_merge_operation__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__cow_merge_operation__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const uint32_t
    chromeos_update_engine__partition_update__fec_roots__default_value = 2u;
static const ProtobufCFieldDescriptor
    chromeos_update_engine__partition_update__field_descriptors[20] = {
        {
            "partition_name", 1, PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, partition_name),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "run_postinstall", 2, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     has_run_postinstall),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, run_postinstall),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "postinstall_path", 3, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, postinstall_path),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "filesystem_type", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, filesystem_type),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "new_partition_signature", 5, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     n_new_partition_signature),
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     new_partition_signature),
            &chromeos_update_engine__signatures__signature__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "old_partition_info", 6, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, old_partition_info),
            &chromeos_update_engine__partition_info__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "new_partition_info", 7, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, new_partition_info),
            &chromeos_update_engine__partition_info__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "operations", 8, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__PartitionUpdate, n_operations),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, operations),
            &chromeos_update_engine__install_operation__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "postinstall_optional", 9, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     has_postinstall_optional),
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     postinstall_optional),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "hash_tree_data_extent", 10, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     hash_tree_data_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "hash_tree_extent", 11, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, hash_tree_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "hash_tree_algorithm", 12, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     hash_tree_algorithm),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "hash_tree_salt", 13, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BYTES,
            offsetof(ChromeosUpdateEngine__PartitionUpdate, has_hash_tree_salt),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, hash_tree_salt),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "fec_data_extent", 14, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, fec_data_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "fec_extent", 15, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, fec_extent),
            &chromeos_update_engine__extent__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "fec_roots", 16, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__PartitionUpdate, has_fec_roots),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, fec_roots), NULL,
            &chromeos_update_engine__partition_update__fec_roots__default_value,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "version", 17, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__PartitionUpdate, version), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "merge_operations", 18, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__PartitionUpdate, n_merge_operations),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, merge_operations),
            &chromeos_update_engine__cow_merge_operation__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "estimate_cow_size", 19, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     has_estimate_cow_size),
            offsetof(ChromeosUpdateEngine__PartitionUpdate, estimate_cow_size),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "estimate_op_count_max", 20, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     has_estimate_op_count_max),
            offsetof(ChromeosUpdateEngine__PartitionUpdate,
                     estimate_op_count_max),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__partition_update__field_indices_by_name[] = {
        18, /* field[18] = estimate_cow_size */
        19, /* field[19] = estimate_op_count_max */
        13, /* field[13] = fec_data_extent */
        14, /* field[14] = fec_extent */
        15, /* field[15] = fec_roots */
        3,  /* field[3] = filesystem_type */
        11, /* field[11] = hash_tree_algorithm */
        9,  /* field[9] = hash_tree_data_extent */
        10, /* field[10] = hash_tree_extent */
        12, /* field[12] = hash_tree_salt */
        17, /* field[17] = merge_operations */
        6,  /* field[6] = new_partition_info */
        4,  /* field[4] = new_partition_signature */
        5,  /* field[5] = old_partition_info */
        7,  /* field[7] = operations */
        0,  /* field[0] = partition_name */
        8,  /* field[8] = postinstall_optional */
        2,  /* field[2] = postinstall_path */
        1,  /* field[1] = run_postinstall */
        16, /* field[16] = version */
};
static const ProtobufCIntRange
    chromeos_update_engine__partition_update__number_ranges[1 + 1] = {{1, 0},
                                                                      {0, 20}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__partition_update__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.PartitionUpdate",
        "PartitionUpdate",
        "ChromeosUpdateEngine__PartitionUpdate",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__PartitionUpdate),
        20,
        chromeos_update_engine__partition_update__field_descriptors,
        chromeos_update_engine__partition_update__field_indices_by_name,
        1,
        chromeos_update_engine__partition_update__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__partition_update__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__dynamic_partition_group__field_descriptors[3] = {
        {
            "name", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__DynamicPartitionGroup, name), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "size", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__DynamicPartitionGroup, has_size),
            offsetof(ChromeosUpdateEngine__DynamicPartitionGroup, size), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "partition_names", 3, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_STRING,
            offsetof(ChromeosUpdateEngine__DynamicPartitionGroup,
                     n_partition_names),
            offsetof(ChromeosUpdateEngine__DynamicPartitionGroup,
                     partition_names),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__dynamic_partition_group__field_indices_by_name[] = {
        0, /* field[0] = name */
        2, /* field[2] = partition_names */
        1, /* field[1] = size */
};
static const ProtobufCIntRange
    chromeos_update_engine__dynamic_partition_group__number_ranges[1 + 1] = {
        {1, 0}, {0, 3}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__dynamic_partition_group__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.DynamicPartitionGroup",
        "DynamicPartitionGroup",
        "ChromeosUpdateEngine__DynamicPartitionGroup",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__DynamicPartitionGroup),
        3,
        chromeos_update_engine__dynamic_partition_group__field_descriptors,
        chromeos_update_engine__dynamic_partition_group__field_indices_by_name,
        1,
        chromeos_update_engine__dynamic_partition_group__number_ranges,
        (ProtobufCMessageInit)
            chromeos_update_engine__dynamic_partition_group__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__vabcfeature_set__field_descriptors[2] = {
        {
            "threaded", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__VABCFeatureSet, has_threaded),
            offsetof(ChromeosUpdateEngine__VABCFeatureSet, threaded), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "batch_writes", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__VABCFeatureSet, has_batch_writes),
            offsetof(ChromeosUpdateEngine__VABCFeatureSet, batch_writes), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__vabcfeature_set__field_indices_by_name[] = {
        1, /* field[1] = batch_writes */
        0, /* field[0] = threaded */
};
static const ProtobufCIntRange
    chromeos_update_engine__vabcfeature_set__number_ranges[1 + 1] = {{1, 0},
                                                                     {0, 2}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__vabcfeature_set__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.VABCFeatureSet",
        "VABCFeatureSet",
        "ChromeosUpdateEngine__VABCFeatureSet",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__VABCFeatureSet),
        2,
        chromeos_update_engine__vabcfeature_set__field_descriptors,
        chromeos_update_engine__vabcfeature_set__field_indices_by_name,
        1,
        chromeos_update_engine__vabcfeature_set__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__vabcfeature_set__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__dynamic_partition_metadata__field_descriptors[7] = {
        {
            "groups", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata, n_groups),
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata, groups),
            &chromeos_update_engine__dynamic_partition_group__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "snapshot_enabled", 2, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     has_snapshot_enabled),
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     snapshot_enabled),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "vabc_enabled", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     has_vabc_enabled),
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     vabc_enabled),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "vabc_compression_param", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     vabc_compression_param),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "cow_version", 5, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     has_cow_version),
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     cow_version),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "vabc_feature_set", 6, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     vabc_feature_set),
            &chromeos_update_engine__vabcfeature_set__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "compression_factor", 7, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     has_compression_factor),
            offsetof(ChromeosUpdateEngine__DynamicPartitionMetadata,
                     compression_factor),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__dynamic_partition_metadata__field_indices_by_name
        [] = {
            6, /* field[6] = compression_factor */
            4, /* field[4] = cow_version */
            0, /* field[0] = groups */
            1, /* field[1] = snapshot_enabled */
            3, /* field[3] = vabc_compression_param */
            2, /* field[2] = vabc_enabled */
            5, /* field[5] = vabc_feature_set */
};
static const ProtobufCIntRange
    chromeos_update_engine__dynamic_partition_metadata__number_ranges[1 + 1] = {
        {1, 0}, {0, 7}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__dynamic_partition_metadata__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.DynamicPartitionMetadata",
        "DynamicPartitionMetadata",
        "ChromeosUpdateEngine__DynamicPartitionMetadata",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__DynamicPartitionMetadata),
        7,
        chromeos_update_engine__dynamic_partition_metadata__field_descriptors,
        chromeos_update_engine__dynamic_partition_metadata__field_indices_by_name,
        1,
        chromeos_update_engine__dynamic_partition_metadata__number_ranges,
        (ProtobufCMessageInit)
            chromeos_update_engine__dynamic_partition_metadata__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__apex_info__field_descriptors[4] = {
        {
            "package_name", 1, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__ApexInfo, package_name), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "version", 2, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_INT64,
            offsetof(ChromeosUpdateEngine__ApexInfo, has_version),
            offsetof(ChromeosUpdateEngine__ApexInfo, version), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "is_compressed", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__ApexInfo, has_is_compressed),
            offsetof(ChromeosUpdateEngine__ApexInfo, is_compressed), NULL, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "decompressed_size", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT64,
            offsetof(ChromeosUpdateEngine__ApexInfo, has_decompressed_size),
            offsetof(ChromeosUpdateEngine__ApexInfo, decompressed_size), NULL,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__apex_info__field_indices_by_name[] = {
        3, /* field[3] = decompressed_size */
        2, /* field[2] = is_compressed */
        0, /* field[0] = package_name */
        1, /* field[1] = version */
};
static const ProtobufCIntRange
    chromeos_update_engine__apex_info__number_ranges[1 + 1] = {{1, 0}, {0, 4}};
const ProtobufCMessageDescriptor chromeos_update_engine__apex_info__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.ApexInfo",
        "ApexInfo",
        "ChromeosUpdateEngine__ApexInfo",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__ApexInfo),
        4,
        chromeos_update_engine__apex_info__field_descriptors,
        chromeos_update_engine__apex_info__field_indices_by_name,
        1,
        chromeos_update_engine__apex_info__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__apex_info__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    chromeos_update_engine__apex_metadata__field_descriptors[1] = {
        {
            "apex_info", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__ApexMetadata, n_apex_info),
            offsetof(ChromeosUpdateEngine__ApexMetadata, apex_info),
            &chromeos_update_engine__apex_info__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__apex_metadata__field_indices_by_name[] = {
        0, /* field[0] = apex_info */
};
static const ProtobufCIntRange
    chromeos_update_engine__apex_metadata__number_ranges[1 + 1] = {{1, 0},
                                                                   {0, 1}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__apex_metadata__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.ApexMetadata",
        "ApexMetadata",
        "ChromeosUpdateEngine__ApexMetadata",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__ApexMetadata),
        1,
        chromeos_update_engine__apex_metadata__field_descriptors,
        chromeos_update_engine__apex_metadata__field_indices_by_name,
        1,
        chromeos_update_engine__apex_metadata__number_ranges,
        (ProtobufCMessageInit)chromeos_update_engine__apex_metadata__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
static const uint32_t
    chromeos_update_engine__delta_archive_manifest__block_size__default_value =
        4096u;
static const uint32_t
    chromeos_update_engine__delta_archive_manifest__minor_version__default_value =
        0u;
static const ProtobufCFieldDescriptor
    chromeos_update_engine__delta_archive_manifest__field_descriptors[10] = {
        {
            "block_size", 3, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_block_size),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, block_size),
            NULL,
            &chromeos_update_engine__delta_archive_manifest__block_size__default_value,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "signatures_offset", 4, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_signatures_offset),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     signatures_offset),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "signatures_size", 5, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT64,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_signatures_size),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     signatures_size),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "minor_version", 12, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_UINT32,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_minor_version),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, minor_version),
            NULL,
            &chromeos_update_engine__delta_archive_manifest__minor_version__default_value,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "partitions", 13, PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, n_partitions),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, partitions),
            &chromeos_update_engine__partition_update__descriptor, NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "max_timestamp", 14, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT64,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_max_timestamp),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, max_timestamp),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "dynamic_partition_metadata", 15, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     dynamic_partition_metadata),
            &chromeos_update_engine__dynamic_partition_metadata__descriptor,
            NULL, 0,      /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "partial_update", 16, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BOOL,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     has_partial_update),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     partial_update),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
        {
            "apex_info", 17, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, n_apex_info),
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest, apex_info),
            &chromeos_update_engine__apex_info__descriptor, NULL, 0, /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "security_patch_level", 18, PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
            offsetof(ChromeosUpdateEngine__DeltaArchiveManifest,
                     security_patch_level),
            NULL, NULL, 0, /* flags */
            0, NULL, NULL  /* reserved1,reserved2, etc */
        },
};
static const unsigned
    chromeos_update_engine__delta_archive_manifest__field_indices_by_name[] = {
        8, /* field[8] = apex_info */
        0, /* field[0] = block_size */
        6, /* field[6] = dynamic_partition_metadata */
        5, /* field[5] = max_timestamp */
        3, /* field[3] = minor_version */
        7, /* field[7] = partial_update */
        4, /* field[4] = partitions */
        9, /* field[9] = security_patch_level */
        1, /* field[1] = signatures_offset */
        2, /* field[2] = signatures_size */
};
static const ProtobufCIntRange
    chromeos_update_engine__delta_archive_manifest__number_ranges[2 + 1] = {
        {3, 0}, {12, 3}, {0, 10}};
const ProtobufCMessageDescriptor
    chromeos_update_engine__delta_archive_manifest__descriptor = {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "chromeos_update_engine.DeltaArchiveManifest",
        "DeltaArchiveManifest",
        "ChromeosUpdateEngine__DeltaArchiveManifest",
        "chromeos_update_engine",
        sizeof(ChromeosUpdateEngine__DeltaArchiveManifest),
        10,
        chromeos_update_engine__delta_archive_manifest__field_descriptors,
        chromeos_update_engine__delta_archive_manifest__field_indices_by_name,
        2,
        chromeos_update_engine__delta_archive_manifest__number_ranges,
        (ProtobufCMessageInit)
            chromeos_update_engine__delta_archive_manifest__init,
        NULL,
        NULL,
        NULL /* reserved[123] */
};
